---
title: PMTiles - overture
output: 
  bookdown::html_vignette2:
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 8,
  comment = "#>"
)
hook_output <- knitr::knit_hooks$get("output")
knitr::knit_hooks$set(output = function(x, options) {
   lines <- options$output.lines
   if (is.null(lines)) {
     return(hook_output(x, options))  # pass to default hook
   }
   x <- unlist(strsplit(x, "\n"))
   more <- "..."
   if (length(lines)==1) {        # first n lines
     if (length(x) > lines) {
       # truncate the output, but add ....
       x <- c(head(x, lines), more)
     }
   } else {
     x <- c(more, x[lines], more)
   }
   # paste these lines together
   x <- paste(c(x, ""), collapse = "\n")
   hook_output(x, options)
 })
#load_all("../tmap");load_all("../tmap.mapgl");load_all();tmap_mode("maplibre")
```



## Introduction

<to be added, some introduction about PMTiles format>

## Remote PMTiles file

OvertureMaps contain a few very large PMTiles. The following is one with the [buildings](https://docs.overturemaps.org/guides/buildings/), across the World.


```{r, fig.height = 3.5}
urls = tmap_src_overture()

tm_shape(
  urls$building, 
  bbox = "Amsterdam") +
tm_polygons(fill = "#ee7700") +
tm_maplibre(zoom = 14)
```


We can also use a categorical color palette:

```{r, fig.height = 3.5}
library(tmap)
library(tmap.sources)

urls = tmap_src_overture()
meta = tmap_src_meta(urls$buildings)
vars = tmap_src_vars(meta, layer = "building")
cats = tmap_src_cats(meta, layer = "building", var = "subtype")

tm_shape(
  urls$buildings,
  layer = "building",
  bbox = "Amsterdam") +
tm_polygons(
  fill = "subtype",
  fill.scale = tm_scale_categorical(
    levels    = cats$categories,
    values    = cats$palette,
    value.na  = "#ffffff",
    label.na  = "Unknown"
  ),
  fill.legend = tm_legend("Building type")
) +
tm_maplibre(zoom = 14)
```
